name: Pytest

on:
  push:
    paths:
      - '**.**'
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Packages
        run: |
          echo "Working dir is $(pwd)"
          ls -al
          sudo bash ./install.sh --install-service=FALSE
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest requests
      - name: Test with pytest
        run: |
          pytest -v tests/